name: Test
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - awscli
          - go
        include:
          - tool: awscli
            pre-installed: true
          - tool: go
            pre-installed: false
    env:
      GH_TOKEN: ${{ github.token }}
      TOOL: ${{ matrix.tool }}
    steps:
      - uses: actions/checkout@v4
      - run: make -f "${TOOL}.mk" uninstall
        if: ${{ matrix.pre-installed == true || matrix.pre-installed == 'true' }}
      - run: make -f "${TOOL}.mk" install
      - run: make -f "${TOOL}.mk" update
