name: Test
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - awscli
          - kubectl
          - go
          - helm
          - teleport
          - terraform
        include:
          - tool: awscli
            pre-installed: true
          - tool: kubectl
            pre-installed: false
          - tool: go
            pre-installed: false
          - tool: helm
            pre-installed: true
          - tool: teleport
            pre-installed: false
          - tool: terraform
            pre-installed: true
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - run: make uninstall
        working-directory: ${{ matrix.tool }}
        if: ${{ matrix.pre-installed == true || matrix.pre-installed == 'true' }}
      - run: make install
        working-directory: ${{ matrix.tool }}
      - run: make update
        working-directory: ${{ matrix.tool }}
